AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

plugins:
  - rubocop-numbered-params
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-rspec

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 6

Style/Documentation:
  Enabled: false

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
