AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

plugins:
  - rubocop-numbered-params
  - rubocop-rake
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 6

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
